### ISSUE TITLE
Running kafka-proxy in k8s with more then 1 replica

### ISSUE THREAD

**Issue by pkruesi** [grepplabs/kafka-proxy#174]
**kafka-proxy version: 0.3.11**

For our migration we would like to run kafka-proxy in k8s.
I defined a kafka-proxy deployment which is working fine with `replicas: 1` set.
I would like to have at least 3 replicas of the kafka-proxy pods. How can I achieve this? Only setting `replicas: 3` does not work and kafka proxy is not working anymore properly.
Is there a way to get kafka-proxy running with 3 replicas on k8s?

**My current deployment**
```
  ---    
  apiVersion: apps/v1    
  kind: Deployment    
  metadata:    
    name: kafka-proxy    
    labels:     
      app.kubernetes.io/name: kafka-proxy    
    namespace: my-namespace    
  spec:    
    # could not find a way how to run kafka-proxy with multiple replicas!                                                     
    replicas: 1
    selector:    
      matchLabels:    
        app.kubernetes.io/name: kafka-proxy    
    strategy:    
      rollingUpdate:     
        maxSurge: 1    
        maxUnavailable: 0    
    template:    
      metadata:    
        labels:    
          app.kubernetes.io/name: kafka-proxy    
      spec:    
        containers:    
          - name: kafka-proxy    
            image: grepplabs/kafka-proxy:0.3.11    
            imagePullPolicy: IfNotPresent    
            command: [    
              "/opt/kafka-proxy/bin/kafka-proxy", "server",     
              "--bootstrap-server-mapping", "kafka-bootstrap.foo.bar:9092,0.0.0.0:39992" ,    
              "--log-level", "debug",    
              "--log-format=json",    
            ]    
            resources:    
              limits:    
                cpu: "1000m"    
                memory: "1024Mi"    
              requests:    
                cpu: "1000m"    
                memory: "1024Mi"    
            ports:    
              - containerPort: 39992    
                name: kproxy-broker1    
                protocol: TCP    
              - containerPort: 9080                                                                                           
                name: http-metrics                                                                                            
                protocol: TCP                                                                                                 
            readinessProbe:                                                                                                   
              httpGet:                                                                                                        
                path: /health                                                                                                 
                port: 9080
```

Thanks for your help.

**Comment by pkruesi** [comment]
I found the solution. My `command` for the `kafka-proxy server` was wrong and missed the `advhost:advport` values for the `----bootstrap-server-mapping` parameter.

```yaml
---    
  apiVersion: apps/v1    
  kind: Deployment    
  metadata:    
    name: kafka-proxy    
    labels:     
      app.kubernetes.io/name: kafka-proxy    
    namespace: my-namespace    
  spec:    
    replicas: 3
    selector:    
      matchLabels:    
        app.kubernetes.io/name: kafka-proxy    
    strategy:    
      rollingUpdate:     
        maxSurge: 1    
        maxUnavailable: 0    
    template:    
      metadata:    
        labels:    
          app.kubernetes.io/name: kafka-proxy    
      spec:    
        containers:    
          - name: kafka-proxy    
            image: grepplabs/kafka-proxy:0.3.11    
            imagePullPolicy: IfNotPresent    
            command: [    
              "/opt/kafka-proxy/bin/kafka-proxy", "server",     
              "--bootstrap-server-mapping", "kafka-bootstrap1.foo.bar:9092,0.0.0.0:39992,kafka-proxy-1.my-namespace.svc.cluster.local:9092" ,  
              "--bootstrap-server-mapping", "kafka-bootstrap2.foo.bar:9092,0.0.0.0:39993,kafka-proxy-2.my-namespace.svc.cluster.local:9092" ,
              "--bootstrap-server-mapping", "kafka-bootstrap3.foo.bar:9092,0.0.0.0:39994,kafka-proxy-3.my-namespace.svc.cluster.local:9092" ,
              "--log-level", "debug",    
              "--log-format=json",    
            ]    
            resources:    
              limits:    
                cpu: "1000m"    
                memory: "1024Mi"    
              requests:    
                cpu: "1000m"    
                memory: "1024Mi"    
            ports:    
              - containerPort: 39992    
                name: kproxy-broker1    
                protocol: TCP    
              - containerPort: 9080                                                                                           
                name: http-metrics                                                                                            
                protocol: TCP                                                                                                 
            readinessProbe:                                                                                                   
              httpGet:                                                                                                        
                path: /health                                                                                                 
                port: 9080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kafka-proxy
  name: kafka-proxy-1
  namespace: my-namespace
spec:
  type: ClusterIP
  ports:
    - name: kafka-proxy-1
      port: 9092
      targetPort: 39992
  selector:
    app.kubernetes.io/name: kafka-proxy
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kafka-proxy
  name: kafka-proxy-1
  namespace: my-namespace
spec:
  type: ClusterIP
  ports:
    - name: kafka-proxy-2
      port: 9092
      targetPort: 39993
  selector:
    app.kubernetes.io/name: kafka-proxy
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kafka-proxy
  name: kafka-proxy-1
  namespace: my-namespace
spec:
  type: ClusterIP
  ports:
    - name: kafka-proxy-3
      port: 9092
      targetPort: 39994
  selector:
    app.kubernetes.io/name: kafka-proxy
```
