### ISSUE TITLE
QUESTION: So what config would I use to simply pass through SASL?

### ISSUE THREAD

**Issue by joncourt** [grepplabs/kafka-proxy#18]
Given the answer to a previous question - that SASL will get passed through by default - does this mean that i configure my java client with the SASL properties for the brokers and it will get passed transparently through the kafka proxy when i use the kafka-proxy as my bootstrap-servers?

I've been fiddling around with the settings to achieve this and i'm up to the point where i'm getting net address mapping not faund for my brokers which appear to have been renamed to b2-<target broker address> (i.e. b2-pkc-ep0ml.ap-southeast-2.aws.confluent.cloud:9092 for the config below). Do i need to configure something in external-server-mappings perhaps - i don't actually understand what `external-server-mappings` actually does - I originally thought it might be instead of bootstrap-server-mapping where the kafka broker is on a host that's not the same as the one the kafka-proxy is on, but that doesn't appear to be so.

I'm presuming some kind of dynamic proxy is set up on the kafka-proxy and the path is `client -> kafka-proxy -> kafka-proxy dynamic proxy -> kafka-brokers`?

I think perhaps I'm a little confused.

# Background
my java client is configured: 
```java
ssl.truststore.location=dev-kafka.truststore.jks
ssl.truststore.password=changeit
ssl.truststore.type=PKCS12
ssl.endpoint.identification.algorithm=https
sasl.mechanism=PLAIN
request.timeout.ms=20000
bootstrap.servers=worker-0.some.domain.name.com:9092
retry.backoff.ms=500
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username\="someusername" password\="somepassword";
security.protocol=SASL_SSL
```

and my kafka-proxy is run as:
```bash
kafka-proxy server \
	--bootstrap-server-mapping "pkc-ep0ml.ap-southeast-2.aws.confluent.cloud:9092,0.0.0.0:9092" \
	--tls-enable \
	--tls-insecure-skip-verify \
	--proxy-listener-tls-enable \
	--proxy-listener-key-file=/root/dev-kafka-server.private.key \
	--proxy-listener-cert-file=/root/dev-kafka-server.signed.cer \
	--dynamic-listeners-disable
```

Error's I'm seeing are:

```bash
INFO[2018-10-08T17:17:51+13:00] New connection for pkc-ep0ml.ap-southeast-2.aws.confluent.cloud:9092 
INFO[2018-10-08T17:17:51+13:00] Reading data from pkc-ep0ml.ap-southeast-2.aws.confluent.cloud:9092 had error: net address mapping for b2-pkc-ep0ml.ap-southeast-2.aws.confluent.cloud:9092 was not found 
```

**Comment by everesio** [comment]
I assume that b2-pkc-ep0ml.ap-southeast-2.aws.confluent.cloud:9092 is an advertised listener sent by the broker.

external-server-mapping is for changing received host:port addresses without starting additional listener. 
I used this configuration for 1 Proxy to 1 Broker setup e.g.  
```
{{ range $i := until (int $.brokers) }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
   name: kafka-gateway-{{ $i }}
   namespace: kafka-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-gateway-{{ $i }}
  template:
    metadata:
      labels:
        app: kafka-gateway-{{ $i }}
    spec:
      containers:
        - name: kafka-gateway
          image: grepplabs/kafka-proxy:latest
          imagePullPolicy: Always
          args:
            - 'server'
            - '--log-format=json'
            - '--dynamic-listeners-disable'
            - '--bootstrap-server-mapping=kafka-{{ $i }}-0:9093,0.0.0.0:32400,kafka-gateway-{{ $i }}-0.{{ $.dnszone }}:32400'
            {{- range $j := until (int $.brokers) }}
            - '--external-server-mapping=kafka-{{ $j }}-0:9093,kafka-gateway-{{ $j }}-0.{{ $.dnszone }}:32400'
            {{- end }}
...
```
