### ISSUE TITLE
Question: msk server in port 443

### ISSUE THREAD

**Issue by rajk0007** [grepplabs/kafka-proxy#32]
My requirement is expose msk in public internet on port 443. I am trying to run this proxy in eks fronting MSK . 

```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-proxy-1
  name: kafka-proxy-1
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: kafka-proxy-1
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: kafka-proxy-1
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-proxy-2
  name: kafka-proxy-2
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: kafka-proxy-2
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: kafka-proxy-2
  sessionAffinity: None
  type: LoadBalancer
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-proxy-3
  name: kafka-proxy-3
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: kafka-proxy-3
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: kafka-proxy-3
  sessionAffinity: None
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: kafka-proxy-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-proxy-1
  template:
    metadata:
      labels:
        app: kafka-proxy-1
    spec:
      containers:
        - name: kafka-proxy
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "SYS_TIME","NET_BIND_SERVICE"]
          image: grepplabs/kafka-proxy:latest
          args:
            - 'server'
            - '--log-format=json'
            - '--bootstrap-server-mapping=b-1.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094,0.0.0.0:443,a572bcec9048311ea874d02324e2a15c-102380383.us-east-1.elb.amazonaws.com:443'
            - '--external-server-mapping=b-1.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094,a572bcec9048311ea874d02324e2a15c-102380383.us-east-1.elb.amazonaws.com:443'
            - '--external-server-mapping=b-2.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094,a573b1e97048311ea874d02324e2a15c-2011622944.us-east-1.elb.amazonaws.com:443'
            - '--external-server-mapping=b-3.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094,a574a0444048311ea874d02324e2a15c-972090528.us-east-1.elb.amazonaws.com:443'
            - '--tls-enable'
            - '--log-level=debug'
            - '--dynamic-listeners-disable'
            - '--tls-insecure-skip-verify'
            - '--proxy-request-buffer-size=32768'
            - '--proxy-response-buffer-size=32768'
            - '--proxy-listener-read-buffer-size=32768'
            - '--proxy-listener-write-buffer-size=131072'
            - '--kafka-connection-read-buffer-size=131072'
            - '--kafka-connection-write-buffer-size=32768'
          ports:
          - name: kafka-port1
            containerPort: 443


---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: kafka-proxy-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-proxy-2
  template:
    metadata:
      labels:
        app: kafka-proxy-2
    spec:
      containers:
        - name: kafka-proxy
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "SYS_TIME","NET_BIND_SERVICE"]
          image: grepplabs/kafka-proxy:latest
          args:
            - 'server'
            - '--log-format=json'
            - '--bootstrap-server-mapping=b-2.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094,0.0.0.0:443,a573b1e97048311ea874d02324e2a15c-2011622944.us-east-1.elb.amazonaws.com:443'
            - '--external-server-mapping=b-1.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094,a572bcec9048311ea874d02324e2a15c-102380383.us-east-1.elb.amazonaws.com:443'
            - '--external-server-mapping=b-2.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094,a573b1e97048311ea874d02324e2a15c-2011622944.us-east-1.elb.amazonaws.com:443'
            - '--external-server-mapping=b-3.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094,a574a0444048311ea874d02324e2a15c-972090528.us-east-1.elb.amazonaws.com:443'
            - '--tls-enable'
            - '--log-level=debug'
            - '--dynamic-listeners-disable'
            - '--tls-insecure-skip-verify'
            - '--proxy-request-buffer-size=32768'
            - '--proxy-response-buffer-size=32768'
            - '--proxy-listener-read-buffer-size=32768'
            - '--proxy-listener-write-buffer-size=131072'
            - '--kafka-connection-read-buffer-size=131072'
            - '--kafka-connection-write-buffer-size=32768'
          ports:
          - name: kafka-port2
            containerPort: 443


---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: kafka-proxy-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-proxy-3
  template:
    metadata:
      labels:
        app: kafka-proxy-3
    spec:
      containers:
        - name: kafka-proxy
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "SYS_TIME","NET_BIND_SERVICE"]
          image: grepplabs/kafka-proxy:latest
          args:
            - 'server'
            - '--log-format=json'
            - '--external-server-mapping=b-1.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094,a572bcec9048311ea874d02324e2a15c-102380383.us-east-1.elb.amazonaws.com:443'
            - '--external-server-mapping=b-2.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094,a573b1e97048311ea874d02324e2a15c-2011622944.us-east-1.elb.amazonaws.com:443'
            - '--external-server-mapping=b-3.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094,a574a0444048311ea874d02324e2a15c-972090528.us-east-1.elb.amazonaws.com:443'
            - '--bootstrap-server-mapping=b-3.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094,0.0.0.0:443,a574a0444048311ea874d02324e2a15c-972090528.us-east-1.elb.amazonaws.com:443'
            - '--tls-enable'
            - '--log-level=debug'
            - '--dynamic-listeners-disable'
            - '--tls-insecure-skip-verify'
            - '--proxy-request-buffer-size=32768'
            - '--proxy-response-buffer-size=32768'
            - '--proxy-listener-read-buffer-size=32768'
            - '--proxy-listener-write-buffer-size=131072'
            - '--kafka-connection-read-buffer-size=131072'
            - '--kafka-connection-write-buffer-size=32768'
          ports:
          - name: kafka-port3
            containerPort: 443

```

where *.us-east-1.elb.amazonaws.com:443 are the external ip i get from eks. 

I get this error in my pod

```{"@level":"info","@message":"Starting kafka-proxy version unknown","@timestamp":"2019-11-11T22:45:59Z"}
{"@level":"info","@message":"Bootstrap server b-1.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094 advertised as a572bcec9048311ea874d02324e2a15c-102380383.us-east-1.elb.amazonaws.com:443","@timestamp":"2019-11-11T22:45:59Z"}
{"@level":"info","@message":"External server b-2.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094 advertised as a573b1e97048311ea874d02324e2a15c-2011622944.us-east-1.elb.amazonaws.com:443","@timestamp":"2019-11-11T22:45:59Z"}
{"@level":"info","@message":"External server b-3.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094 advertised as a574a0444048311ea874d02324e2a15c-972090528.us-east-1.elb.amazonaws.com:443","@timestamp":"2019-11-11T22:45:59Z"}
{"@level":"info","@message":"Listening on 0.0.0.0:443 ([::]:443) for remote b-1.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094","@timestamp":"2019-11-11T22:45:59Z"}
{"@level":"info","@message":"Ready for new connections","@timestamp":"2019-11-11T22:45:59Z"}
{"@level":"info","@message":"New connection for b-1.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094","@timestamp":"2019-11-11T22:46:01Z"}
{"@level":"info","@message":"Client closed local connection on 20.10.3.191:443 from 20.10.1.197:39176 (b-1.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094)","@timestamp":"2019-11-11T22:46:01Z"}
{"@level":"info","@message":"New connection for b-1.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094","@timestamp":"2019-11-11T22:46:05Z"}
{"@level":"info","@message":"Client closed local connection on 20.10.3.191:443 from 20.10.2.185:7332 (b-1.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094)","@timestamp":"2019-11-11T22:46:05Z"}
{"@level":"info","@message":"New connection for b-1.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094","@timestamp":"2019-11-11T22:46:09Z"}
{"@level":"info","@message":"Client closed local connection on 20.10.3.191:443 from 20.10.3.252:36298 (b-1.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094)","@timestamp":"2019-11-11T22:46:09Z"}
{"@level":"info","@message":"New connection for b-1.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094","@timestamp":"2019-11-11T22:46:11Z"}
{"@level":"info","@message":"Client closed local connection on 20.10.3.191:443 from 20.10.1.197:39186 (b-1.pdp-kafka.h5u916.c3.kafka.us-east-1.amazonaws.com:9094)","@timestamp":"2019-11-11T22:46:11Z"}```
